const LinkSection = () => (
    <>
        <ul>
            <li>
                <a
                    rel="noreferrer"
                    target="_blank"
                    href="https://www.linkedin.com/in/abdur-rahman-shaik-55b88a202/"
                >
                    LinkedIn
                </a>
            </li>
            <li>
                <a
                    rel="noreferrer"
                    target="_blank"
                    href="https://leetcode.com/Abdur1/">
                    LeetCode
                </a>
            </li>
            <li>
                <a
                    rel="noreferrer"
                    target="_blank"
                    href="https://github.com/Abdur1R">
                    GitHub
                </a>
            </li>
            <li>
                <a
                    rel="noreferrer"
                    target="_blank"
                    href="https://abdur1r.github.io/training-ui/">
                    Website
                </a>
            </li>
        </ul>
    </>
);

export default LinkSection;